# version: "3.7"
# services:
#   web1:
#     build: ./quote_gen
#     container_name: gen
#     ports:
#       - "5000:5000"
#   web2:
#     build: ./quote_disp
#     container_name: disp
#     ports:
#       - "5001:5001"
#     depends_on:
#       - web1

version: "3.7"
services:
  web1:
    build: ./quote_gen
    # container_name: gen
    ports:
      - "5000-5002:5000"
    volumes:
      - ./quote_gen:/app  # Mount the project directory into the container
  web2:
    build: ./quote_disp
    # container_name: disp
    ports:
      - "5003-5005:5001"
    depends_on:
      - web1
    volumes:
      - ./quote_disp:/app  # Mount the project directory into the container
